import type { JobType } from "./types"

export async function fetchJobs(): Promise<JobType[]> {
  const jobs: JobType[] = [
    {
      id: 7,
      title: "Data Scientist",
      company: "Analytics Pro",
      type: "Full-time",
      location: "Chicago, IL",
      experience: "3+ years",
      postedAt: "1 week ago",
      description: "Expert in machine learning and data analysis needed",
    },
    {
      id: 8,
      title: "Product Manager",
      company: "ProductLabs",
      type: "Full-time",
      location: "Denver, CO",
      experience: "5+ years",
      postedAt: "3 days ago",
      description: "Technical product manager for our SaaS platform",
    },
    {
      id: 9,
      title: "QA Engineer",
      company: "Quality Tech",
      type: "Full-time",
      location: "Portland, OR",
      experience: "2+ years",
      postedAt: "4 days ago",
      description: "Automation testing expert needed for our QA team",
    },
    {
      id: 10,
      title: "Security Engineer",
      company: "SecureNet",
      type: "Full-time",
      location: "Washington, DC",
      experience: "4+ years",
      postedAt: "1 week ago",
      description: "Cybersecurity expert for our security team",
    },
    {
      id: 11,
      title: "Junior Frontend Developer",
      company: "StartupHub",
      type: "Full-time",
      location: "Miami, FL",
      experience: "1+ years",
      postedAt: "2 days ago",
      description: "Entry-level position for React developers",
    },
    {
      id: 12,
      title: "Systems Architect",
      company: "ArchitecturePro",
      type: "Full-time",
      location: "San Jose, CA",
      experience: "7+ years",
      postedAt: "6 days ago",
      description: "Senior architect for cloud infrastructure",
    },
    {
      id: 13,
      title: "Database Administrator",
      company: "DataCore",
      type: "Full-time",
      location: "Phoenix, AZ",
      experience: "5+ years",
      postedAt: "3 days ago",
      description: "PostgreSQL and MongoDB expert needed",
    },
    {
      id: 14,
      title: "Technical Writer",
      company: "DocuTech",
      type: "Part-time",
      location: "Remote",
      experience: "2+ years",
      postedAt: "1 week ago",
      description: "Documentation specialist for API and technical content",
    },
    {
      id: 15,
      title: "ML Engineer",
      company: "AI Solutions",
      type: "Full-time",
      location: "San Diego, CA",
      experience: "3+ years",
      postedAt: "4 days ago",
      description: "Machine learning expert for AI products",
    },
    {
      id: 16,
      title: "Blockchain Developer",
      company: "CryptoTech",
      type: "Full-time",
      location: "Miami, FL",
      experience: "2+ years",
      postedAt: "5 days ago",
      description: "Smart contract and blockchain development",
    },
    {
      id: 17,
      title: "Cloud Engineer",
      company: "CloudOps",
      type: "Full-time",
      location: "Atlanta, GA",
      experience: "4+ years",
      postedAt: "2 days ago",
      description: "Multi-cloud platform expert needed",
    },
    {
      id: 18,
      title: "Frontend Intern",
      company: "WebLearn",
      type: "Internship",
      location: "Remote",
      experience: "0-1 year",
      postedAt: "1 day ago",
      description: "Learn and grow with our frontend team",
    }
  ]

  console.log('Total jobs:', jobs.length)
  return jobs
} 